apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo-1
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: Always
  nodeSelector:
    disktype: ssd
  tolerations:
  - key: "key"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"
  - key: "key"
    operator: "Equal"
    value: "value1"
    effect: "NoExecute"